"""
Ingest and sample.
"""

from pathlib import Path

import duckdb

# ----------------------------------------------------------------------------------------------------------------------
# Import Local Functionality
from training.job.utils.logging import setup_logger


def run(input_dir: Path, output_dir: Path, config: dict) -> Path:
    """
    Ingest data into the pipeline and save them for future use.

    :param input_dir: Directory containing the configured raw CSV files.
    :param output_dir: Directory in which to write training.csv.
    :param config: Training configuration containing file names, join key and target.
    :param max_rows: Maximum transaction rows to read; None loads all rows.

    :return: Path to the processed training CSV.
    """
    logger = setup_logger()

    # Capture data path
    train_path = input_dir / config["train_file"]

    # Load training data
    df_train = duckdb.read_csv(train_path)

    # Take the sample
    df_sample = df_train.query(
        "df_train",
        f"""
        SELECT *
        FROM df_train
        USING SAMPLE reservoir({config["sample_rows"]} ROWS) REPEATABLE ({config["random_seed"]})
        """,
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Persist the stage output for this run or a later training job

    # Create the Kaggle working directory or its local equivalent when required
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "train.csv"
    df_sample.to_csv(str(output_path))
    logger.info(
        f"Ingested training data with {len(df_sample)} rows and {len(df_sample.columns)} columns to {output_path}"
    )

    # ------------------------------------------------------------------------------------------------------------------
    # Save output for future runs

    if config.get("publish_ingested_dataset", False):
        import kagglehub

        kagglehub.dataset_upload(
            config["ingested_dataset_handle"],
            str(output_dir),
            version_notes=f"Generated by the ingest node: {len(df_sample)} rows.",
        )
        logger.info("Saved ingestion data.")

    return output_path
